16 Identity
Catarina98/Grocify pull request #15
Opened 2024-01-09 09:59 UTC by jessywork

User repository, service, controller, request model and response model.
LoginRequestModel
RegisterResponseModel
Exceptions

2024-01-09 16:58 UTC, Catarina98 requested changes

2024-01-09 16:58 UTC, Catarina98 commented on GrocifyApp.API/Controllers/AuthController.cs
> +            var getUser = await _userService.GetUserByEmail(user.Email); //I cant use CheckEmailExists because this method needs id too
remove comment

2024-01-09 16:58 UTC, Catarina98 commented on GrocifyApp.API/Models/ResponseModels/BadRequestModel.cs
> +    public class BadRequestModel //this is request or response?
response

2024-01-09 16:58 UTC, Catarina98 commented on GrocifyApp.API/Models/ResponseModels/UserResponseModel.cs
> +        public required string Password { get; set; } = String.Empty; //string.Empty needed?
only if you not make Password required

2024-01-09 16:58 UTC, Catarina98 commented on GrocifyApp.DAL/Exceptions/EmailExistsException.cs
> +        public EmailExistsException(string message) : base(message)
please remove both

2024-01-09 16:58 UTC, Catarina98 commented on GrocifyApp.DAL/Exceptions/EmailExistsException.cs
> +        public EmailExistsException()
make it:

public EmailExistException(string message) : base(GenericConsts.Exceptions.EmailAlreadyTaken)
{
}

2024-01-09 16:58 UTC, Catarina98 commented on GrocifyApp.BLL/Implementations/UserService.cs
> +                throw new EmailExistsException(GenericConsts.Exceptions.EmailAlreadyTaken);
see EmailExistsException file comments, and remove this argument here

2024-01-09 16:58 UTC, Catarina98 commented on GrocifyApp.DAL/Repositories/Implementations/UserRepository.cs
> +            return user; //Possible null reference return
make return object be nullable User?

you need to change UserService as well

2024-01-09 19:27 UTC, jessywork commented on GrocifyApp.API/Controllers/AuthController.cs
> +                var errors = new List<string> { GenericConsts.Errors.UserPasswordIncorrect }; //and if we use the consts from DAL? If so, we only have one folder for consts, it seems more easier to s
Did you see this comment?

2024-01-09 19:27 UTC, jessywork commented on GrocifyApp.API/Models/RequestModels/UserRequestModel.cs
> +        public string ConfirmPassword { get; set; } = String.Empty; //string.Empty needed? //i cant make this required because of line 84 of AuthController
Did you see this comment?

2024-01-10 14:34 UTC, Catarina98 requested changes

2024-01-10 14:34 UTC, Catarina98 commented on GrocifyApp.API/Models/RequestModels/LoginRequestModel.cs
> +        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "Please enter a valid email address.")] //const??
const

2024-01-10 14:34 UTC, Catarina98 commented on GrocifyApp.API/Models/ResponseModels/BadResponseModel.cs
> +    public class BadResponseModel //this is request or response?
remove comment

2024-01-10 14:34 UTC, Catarina98 commented on GrocifyApp.API/Models/ResponseModels/UserResponseModel.cs
> +        /// <example>Password</example>
remove Password e ConfirmPassword

2024-01-10 14:34 UTC, Catarina98 commented on GrocifyApp.DAL/Exceptions/EmailExistsException.cs
> +        public EmailExistsException(string message) : base(message)
try again

2024-01-10 14:44 UTC, Catarina98 approved these changes

2024-01-10 14:45 UTC, merged