Login fe
Catarina98/Grocify pull request #19
Opened 2024-01-12 17:26 UTC by Catarina98

2024-01-15 17:22 UTC, jessywork requested changes

2024-01-15 17:22 UTC, jessywork commented on GrocifyApp.API/Controllers/AuthController.cs
> +            //return token;
remove

2024-01-15 17:22 UTC, jessywork commented on GrocifyApp.UI/src/App.jsx
> +    const isAuthenticated = localStorage.getItem('token'); // Check if the user is authenticated
put the comment above this line

2024-01-15 17:22 UTC, jessywork commented on GrocifyApp.UI/src/App.jsx
> +            <div className="App">
why do you need this div?

2024-01-16 10:13 UTC, Catarina98 commented on GrocifyApp.UI/src/App.jsx
> +            <div className="App">
later in css we will use that class

2024-01-16 11:09 UTC, jessywork approved these changes

2024-01-16 11:09 UTC, merged