reorganized settings
Catarina98/Grocify pull request #31
Opened 2024-01-25 16:30 UTC by Catarina98

2024-01-25 17:29 UTC, jessywork requested changes

2024-01-25 17:29 UTC, jessywork commented on GrocifyApp.UI/src/App.jsx
> +                    <Route index element={isAuthenticated ? <Navigate to={AppRoutes.Settings} /> : <LoginForm />} />
why did you move settings to here?

2024-01-25 17:29 UTC, jessywork commented on GrocifyApp.UI/src/components/Logout.jsx
> +      {/* You can add a loading spinner or any other UI elements here */}
add TODO for implementation later

2024-01-25 17:29 UTC, jessywork commented on GrocifyApp.UI/src/pages/Settings.jsx
> +//Internal components
wow, nice organization... 10 of 10

2024-01-25 17:29 UTC, jessywork commented on GrocifyApp.UI/src/pages/Settings.jsx
> +    const [searchInput, setSearchInput] = useState(''); //change to darkMode not false
wrong comment

2024-01-25 17:29 UTC, jessywork commented on GrocifyApp.UI/src/pages/Settings.jsx
> +                    link: () => setDarkMode(), // Pass the function
setDarkMode(!darkMode) ?

2024-01-25 17:32 UTC, Catarina98 commented on GrocifyApp.UI/src/App.jsx
> +                    <Route index element={isAuthenticated ? <Navigate to={AppRoutes.Settings} /> : <LoginForm />} />
to be more organized, first route Logout, second: if authenticated: Settings, else: Login

2024-01-25 17:34 UTC, Catarina98 commented on GrocifyApp.UI/src/pages/Settings.jsx
> +//Internal components
I want to thank chatGPT for all the support, and also my friends and family for never giving up on me.

2024-01-26 11:45 UTC, jessywork approved these changes

2024-01-26 11:45 UTC, merged