Darkmode db
Catarina98/Grocify pull request #33
Opened 2024-01-29 14:17 UTC by jessywork

2024-01-30 10:45 UTC, Catarina98 requested changes

2024-01-30 10:45 UTC, Catarina98 commented on GrocifyApp.API/Controllers/GenericController.cs
> +    //[Authorize]
remove comment

2024-01-30 10:45 UTC, Catarina98 commented on GrocifyApp.UI/src/pages/Settings.jsx
> +            var p = props.userAuth.password; //change
User is a special entity, so we will not use the Update endpoint from Generic. Please create a new enpoint: "ToggleDarkMode". You don't need to pass information from user. You just need to pass the token in Header, and in the API you will have access to the authenticated user.

2024-01-30 10:45 UTC, Catarina98 commented on GrocifyApp.API/Controllers/AuthController.cs
> +            User = new UserResponseModel() { Id = getUser.Id, Email = getUser.Email, Name = getUser.Name, HouseId = houseId, Password = getUser.Password, ConfirmPassword = getUser.Password };
revert this changes, never return the users passwords!

2024-01-30 10:45 UTC, Catarina98 commented on GrocifyApp.API/Models/ResponseModels/UserResponseModel.cs
> +        /// <example>Password</example>
Remove Password and ConfirmPassword

2024-01-30 10:45 UTC, Catarina98 commented on GrocifyApp.UI/src/pages/Settings.jsx
> +            var p = props.userAuth.password; //change
To pass Token:

if (localStorage.getItem('token') == undefined) {
return;
}

const response = await fetch(api/User/ToggleDarkMode, {
method: 'PUT',
headers: {
'Content-Type': 'application/json',
'Authorization': Bearer ${localStorage.getItem('token')},
},
});

2024-01-30 10:45 UTC, Catarina98 commented on GrocifyApp.UI/src/App.jsx
> +            const response = await fetch(`api/User/${userId}`, {
remove this call to API. when you do the login, you have the information of the user, with DarkMode. So, you can save darkmode in localStorage, as you do for token. And have no need to always make this call at the beggining, what do you think?

2024-01-30 10:45 UTC, Catarina98 commented on GrocifyApp.UI/src/pages/Settings.jsx
> +            var p = props.userAuth.password; //change
if you followed my suggestion of saving darkMode in localStorage, don't forget to update it's value here

2024-01-31 10:09 UTC, Catarina98 requested changes

2024-01-31 10:09 UTC, Catarina98 commented on GrocifyApp.API/Controllers/AuthController.cs
> +                new Claim(ClaimTypes.Name, userAPI.Name),
why Claims Email?

2024-01-31 10:09 UTC, Catarina98 commented on GrocifyApp.API/Controllers/UserController.cs
> +            var emailClaim = User.FindFirst(ClaimTypes.Email);
use Authenticator.User

2024-01-31 10:09 UTC, Catarina98 commented on GrocifyApp.API/Controllers/AuthController.cs
>              {
is it possible to remove userRequestModel and use User instead?

2024-01-31 10:09 UTC, Catarina98 commented on GrocifyApp.API/Models/RequestModels/UserRequestModel.cs
> +        /// <example>false</example>
remove?

2024-01-31 10:09 UTC, Catarina98 commented on GrocifyApp.UI/src/consts/ApiEndpoints.js
> +    User_Endpoint: (userId) => `api/User/${userId}`,
remove User_Endpoint

2024-01-31 10:39 UTC, jessywork commented on GrocifyApp.API/Controllers/AuthController.cs
>              {
we need userRequest to createToken

2024-01-31 10:39 UTC, jessywork commented on GrocifyApp.API/Models/RequestModels/UserRequestModel.cs
> +        /// <example>false</example>
Does not isDarkMode need an example?

2024-01-31 10:39 UTC, jessywork commented on GrocifyApp.API/Controllers/UserController.cs
> +            var emailClaim = User.FindFirst(ClaimTypes.Email);
I don't understand what Authenticator.User is. I thought it was a variable with the data of the authenticator user.
However, User is the authenticated user and only has 3 claims. I added the email in order to call the api and get the user's details

2024-01-31 13:54 UTC, Catarina98 commented on GrocifyApp.API/Controllers/AuthController.cs
>              {
you can pass User to createToken

2024-01-31 13:58 UTC, Catarina98 commented on GrocifyApp.API/Models/RequestModels/UserRequestModel.cs
> +        /// <example>false</example>
remove isDarkMode from RequestModel, is never used

2024-01-31 13:59 UTC, Catarina98 commented on GrocifyApp.API/Controllers/UserController.cs
> +            var emailClaim = User.FindFirst(ClaimTypes.Email);
```cs
[HttpPut("toggleDarkMode")]
public async Task<ActionResult<User>> ToggleDarKMode()
{
    var currentUser = _mapper.Map<User>(AuthController.User);

    currentUser.IsDarkMode = !currentUser.IsDarkMode;

    try
    {
        await _userService.Update(currentUser);
    }
    catch (Exception ex)
    {
        var errors = new List<string> { ex.Message };

        return BadRequest(new BadResponseModel { Errors = errors });
    }

    var userResponseModel = _mapper.Map<UserResponseModel>(currentUser);

    return Ok(userResponseModel);
}
```

Why can't you use AuthController.User? and remove extra Claims

2024-02-01 16:45 UTC, Catarina98 approved these changes

2024-02-01 16:46 UTC, merged